#!/usr/bin/env bash
set -euo pipefail

###############################################################################
# bootstrap.sh — One-time setup for the spatial lakehouse stack
#
# Prerequisites: docker compose up -d  (core stack, no "heavy" profile)
#
# What it does:
#   1. Generate real secrets for garage.toml
#   2. Restart Garage with real config
#   3. Assign Garage node layout (single-node, 10GB capacity)
#   4. Create S3 bucket + access key in Garage
#   5. Patch all config files with the real Garage credentials
#   6. Bootstrap LakeKeeper (accept ToS, create warehouse)
#   7. Restart services so everything connects
###############################################################################

GARAGE="docker exec garage /garage"
DC="docker compose"

echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║   Spatial Lakehouse — Bootstrap              ║"
echo "╚══════════════════════════════════════════════╝"
echo ""

# ── 1. Generate secrets ──────────────────────────────────────────────
echo "① Generating secrets..."
RPC_SECRET=$(openssl rand -hex 32)
ADMIN_TOKEN=$(openssl rand -hex 32)
METRICS_TOKEN=$(openssl rand -hex 32)

# ── 2. Patch garage.toml ─────────────────────────────────────────────
echo "② Writing garage.toml..."
sed -i.bak \
  -e "s|PLACEHOLDER_RPC_SECRET|${RPC_SECRET}|" \
  -e "s|PLACEHOLDER_ADMIN_TOKEN|${ADMIN_TOKEN}|" \
  -e "s|PLACEHOLDER_METRICS_TOKEN|${METRICS_TOKEN}|" \
  garage.toml
rm -f garage.toml.bak

# ── 3. Restart Garage ────────────────────────────────────────────────
echo "③ Restarting Garage with real config..."
$DC restart garage
echo "   Waiting for Garage..."
sleep 5

# ── 4. Assign layout ─────────────────────────────────────────────────
echo "④ Configuring Garage cluster layout..."
NODE_ID=$($GARAGE node id 2>/dev/null | head -n1 | cut -d@ -f1)
if [ -z "$NODE_ID" ]; then
  echo "   ✗ Failed to get Garage node ID. Is Garage running?"
  echo "     Try: docker compose restart garage && sleep 5"
  exit 1
fi
echo "   Node: ${NODE_ID:0:16}…"

$GARAGE layout assign -z dc1 -c 10G "$NODE_ID" 2>/dev/null
$GARAGE layout apply --version 1 2>/dev/null
echo "   Layout applied (10GB single-node)."

# ── 5. Create bucket + key ───────────────────────────────────────────
echo "⑤ Creating bucket 'lakehouse'..."
$GARAGE bucket create lakehouse 2>/dev/null || echo "   (bucket exists)"

echo "   Creating access key..."
KEY_OUTPUT=$($GARAGE key create lakehouse-key 2>&1)

KEY_ID=$(echo "$KEY_OUTPUT" | grep -i "Key ID" | awk '{print $NF}')
SECRET_KEY=$(echo "$KEY_OUTPUT" | grep -i "Secret key" | awk '{print $NF}')

# Fallback: try alternate field names if primary parsing failed
if [ -z "$KEY_ID" ]; then
  KEY_ID=$(echo "$KEY_OUTPUT" | grep -iE "access.key|key.id" | awk '{print $NF}')
fi
if [ -z "$SECRET_KEY" ]; then
  SECRET_KEY=$(echo "$KEY_OUTPUT" | grep -iE "secret.key|secret.access" | awk '{print $NF}')
fi

if [ -z "$KEY_ID" ] || [ -z "$SECRET_KEY" ]; then
  echo ""
  echo "   ✗ Could not parse key output. Expected lines containing 'Key ID' and 'Secret key'."
  echo "   Raw output from 'garage key new':"
  echo "$KEY_OUTPUT"
  echo ""
  echo "   Manually set GARAGE_KEY_ID and GARAGE_SECRET_KEY in .env and re-run."
  exit 1
fi

echo "   Key ID:     ${KEY_ID}"
echo "   Secret:     ${SECRET_KEY:0:8}…"

$GARAGE bucket allow --read --write --owner lakehouse --key lakehouse-key 2>/dev/null
echo "   Key granted read/write/owner on 'lakehouse'."

# ── 6. Patch all config files ────────────────────────────────────────
echo "⑥ Patching configs with Garage credentials..."

for f in docker-compose.yml create-warehouse.json duckdb-init.sql sedona-defaults.conf; do
  if [ -f "$f" ]; then
    sed -i.bak \
      -e "s|PLACEHOLDER_GARAGE_KEY_ID|${KEY_ID}|g" \
      -e "s|PLACEHOLDER_GARAGE_SECRET_KEY|${SECRET_KEY}|g" \
      "$f" || { echo "   ✗ Failed to patch ${f}"; exit 1; }
    rm -f "${f}.bak"
    echo "   ✓ ${f}"
  else
    echo "   ⚠ Missing ${f} — skipped (expected in project root)"
  fi
done

# ── 7. Save .env ─────────────────────────────────────────────────────
cat > .env <<EOF
# Generated by bootstrap.sh — $(date -Iseconds 2>/dev/null || date)
GARAGE_KEY_ID=${KEY_ID}
GARAGE_SECRET_KEY=${SECRET_KEY}
GARAGE_ADMIN_TOKEN=${ADMIN_TOKEN}
EOF
echo "   ✓ .env (credentials saved)"

# ── 8. Restart services + bootstrap LakeKeeper ───────────────────────
echo "⑦ Restarting LakeKeeper..."
$DC restart lakekeeper
echo "   Waiting for LakeKeeper..."
sleep 5

echo "   Bootstrapping LakeKeeper (ToS + warehouse)..."
# Accept terms of use
BOOT_HTTP=$(curl -s -o /dev/null -w "%{http_code}" \
  -X POST http://localhost:8181/management/v1/bootstrap \
  -H "Content-Type: application/json" \
  --data '{"accept-terms-of-use": true}' 2>/dev/null) || true

if [ "$BOOT_HTTP" = "200" ] || [ "$BOOT_HTTP" = "204" ]; then
  echo "   ✓ Terms of use accepted."
elif [ "$BOOT_HTTP" = "409" ] || [ "$BOOT_HTTP" = "422" ]; then
  echo "   ✓ Already bootstrapped."
else
  echo "   ⚠ Bootstrap returned HTTP ${BOOT_HTTP}. LakeKeeper may not be ready."
  echo "     Retrying in 5 seconds..."
  sleep 5
  BOOT_HTTP=$(curl -s -o /dev/null -w "%{http_code}" \
    -X POST http://localhost:8181/management/v1/bootstrap \
    -H "Content-Type: application/json" \
    --data '{"accept-terms-of-use": true}' 2>/dev/null) || true
  if [ "$BOOT_HTTP" = "200" ] || [ "$BOOT_HTTP" = "204" ]; then
    echo "   ✓ Terms of use accepted (retry succeeded)."
  elif [ "$BOOT_HTTP" = "409" ] || [ "$BOOT_HTTP" = "422" ]; then
    echo "   ✓ Already bootstrapped."
  else
    echo "   ✗ Bootstrap failed with HTTP ${BOOT_HTTP}. Check LakeKeeper logs."
  fi
fi

# Create warehouse
HTTP_CODE=$(curl -sf -o /dev/null -w "%{http_code}" \
  -X POST http://localhost:8181/management/v1/warehouse \
  -H "Content-Type: application/json" \
  --data @create-warehouse.json 2>/dev/null) || true

if [ "$HTTP_CODE" = "201" ] || [ "$HTTP_CODE" = "200" ]; then
  echo "   ✓ Warehouse 'lakehouse' created."
elif [ "$HTTP_CODE" = "409" ]; then
  echo "   ✓ Warehouse 'lakehouse' already exists."
else
  echo "   ⚠ Warehouse creation returned HTTP ${HTTP_CODE}."
  echo "     You may need to create it via the LakeKeeper UI at http://localhost:8181"
fi

# ── 9. Restart DuckDB ────────────────────────────────────────────────
echo "⑧ Restarting DuckDB..."
$DC restart duckdb
sleep 2

# ── Done ─────────────────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║   ✅  Bootstrap complete!                    ║"
echo "╚══════════════════════════════════════════════╝"
echo ""
echo "  Garage S3 ............. http://localhost:3900"
echo "  LakeKeeper UI ......... http://localhost:8181"
echo ""
echo "  DuckDB (interactive):"
echo "    docker compose exec duckdb /duckdb -init /config/init.sql"
echo ""
echo "  SedonaSpark (when needed):"
echo "    docker compose --profile heavy up sedona -d"
echo "    Open http://localhost:8888 for Jupyter"
echo ""
echo "  ── Quick test ──"
echo '  docker compose exec duckdb /duckdb -init /config/init.sql -c "SELECT ST_Point(-104.99, 39.74) AS denver;"'
echo ""
